### PR TITLE
should close  #111

### LINKED ISSUE #111: Build error on commit
A commit caused SvelteKit to fail to build: a762166cf1fe23a543aa6c79593ec7089cbf7862

### PR DESCRIPTION
**Pull request by pkd2512**
### What's in this pull request

- [x] Bug fix
- [ ] New component/feature
- [ ] Documentation update
- [ ] Other

### Description

Tell us what this PR does or link to any related issues that describe the goal here.

### Before submitting, please check that you've

- [ ] Read our [contributing guide](https://github.com/reuters-graphics/bluprint_graphics-kit/blob/master/CONTRIBUTING.md) at some point
- [ ] Formatted you code correctly (i.e., prettier cleaned it up)
- [ ] Documented any new components or features
- [ ] Tagged an editor to review

### CODE REVIEW

File: pages/+page.svelte [hunk 1]
```diff
@@ -13,13 +13,17 @@
...
 
   // Google doc content
   import content from '$locales/en/content.json';
 
   // Styles
   import '@reuters-graphics/graphics-components/scss/main';
   import '$lib/styles/global.scss';
+
+  // Checks if it's on the client side and has access to search params
+  const searchParams = browser && $page.url?.searchParams;
```
Comment (hobbes7878) [inline pages/+page.svelte:26]: Could probably just wrap this condition with the one in the `if` svelte tag below to a simple `isReutersMobileApp` variable, I think.

**Review by hobbes7878 — CHANGES_REQUESTED** [review]

**Review by hobbes7878 — APPROVED** [review]
